apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  REGISTRY_NAME: "tennisleagueacr.azurecr.io"
---
apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
type: Opaque
stringData:
  DB_USER: "yourDatabaseUser"
  DB_PASSWORD: "yourDatabasePassword"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-tennis-league-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tennisleagueapp
  template:
    metadata:
      labels:
        app: tennisleagueapp
    spec:
      containers:
      - name: tennisleagueapp
        image: $(REGISTRY_NAME)/tennisleagueapp:latest # replace with your ACR image
        ports:
        - containerPort: 80
        env: # Map ConfigMap and Secret to environment variables
        - name: REGISTRY_NAME
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: REGISTRY_NAME
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: DB_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: DB_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: tennis-league-service
spec:
  type: LoadBalancer  # Exposes service to the public
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  selector:
    app: tennisleagueapp
