name: Deploy to AKS

on:
  push:
    branches:
      - main

env:
  REGISTRY_NAME: ${{ secrets.REGISTRY_NAME }}
  AZURE_SERVICE_PRINCIPAL: ${{ secrets.AZURE_SERVICE_PRINCIPAL }}
  AZURE_SERVICE_PASSWORD: ${{ secrets.AZURE_SERVICE_PASSWORD }}
  AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
  DB_USERNAME: ${{ secrets.DB_USERNAME }}
  DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
  AKS_CLUSTER_NAME: ${{ secrets.AKS_CLUSTER_NAME }}
  AKS_RESOURCE_GROUP: ${{ secrets.AKS_RESOURCE_GROUP }}

jobs:
  setup-build-publish-deploy:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Azure ACR Login
      run: az acr login --name $REGISTRY_NAME

    - name: Docker Build and Push to ACR
      run: |
        docker build . -t $REGISTRY_NAME/tennisleagueapp:latest
        docker push $REGISTRY_NAME/tennisleagueapp:latest

    - name: Download kubectl
      run: az aks install-cli

    - name: Get AKS credentials
      run: az aks get-credentials --name $AKS_CLUSTER_NAME --resource-group $AKS_RESOURCE_GROUP

    - name: Deploy to AKS
      run: |
        kubectl apply -f deploy/leagueapp-deploy.yaml
